#pragma once

#include "common.hpp"

class ProcessingUnit;
class MMU;

int op_rlc_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB00
int op_rlc_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB01
int op_rlc_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB02
int op_rlc_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB03
int op_rlc_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB04
int op_rlc_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB05
int op_rlc_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB06
int op_rlc_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB07
int op_rrc_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB08
int op_rrc_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB09
int op_rrc_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB0A
int op_rrc_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB0B
int op_rrc_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB0C
int op_rrc_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB0D
int op_rrc_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB0E
int op_rrc_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB0F
int op_rl_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB10
int op_rl_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB11
int op_rl_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB12
int op_rl_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB13
int op_rl_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB14
int op_rl_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB15
int op_rl_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB16
int op_rl_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB17
int op_rr_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB18
int op_rr_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB19
int op_rr_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB1A
int op_rr_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB1B
int op_rr_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB1C
int op_rr_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB1D
int op_rr_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB1E
int op_rr_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB1F
int op_sla_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB20
int op_sla_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB21
int op_sla_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB22
int op_sla_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB23
int op_sla_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB24
int op_sla_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB25
int op_sla_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB26
int op_sla_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB27
int op_sra_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB28
int op_sra_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB29
int op_sra_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB2A
int op_sra_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB2B
int op_sra_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB2C
int op_sra_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB2D
int op_sra_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB2E
int op_sra_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB2F
int op_swap_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB30
int op_swap_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB31
int op_swap_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB32
int op_swap_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB33
int op_swap_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB34
int op_swap_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB35
int op_swap_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB36
int op_swap_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB37
int op_srl_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB38
int op_srl_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB39
int op_srl_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB3A
int op_srl_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB3B
int op_srl_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB3C
int op_srl_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB3D
int op_srl_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB3E
int op_srl_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB3F
int op_bit_0_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB40
int op_bit_0_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB41
int op_bit_0_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB42
int op_bit_0_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB43
int op_bit_0_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB44
int op_bit_0_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB45
int op_bit_0_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB46
int op_bit_0_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB47
int op_bit_1_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB48
int op_bit_1_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB49
int op_bit_1_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB4A
int op_bit_1_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB4B
int op_bit_1_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB4C
int op_bit_1_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB4D
int op_bit_1_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB4E
int op_bit_1_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB4F
int op_bit_2_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB50
int op_bit_2_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB51
int op_bit_2_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB52
int op_bit_2_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB53
int op_bit_2_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB54
int op_bit_2_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB55
int op_bit_2_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB56
int op_bit_2_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB57
int op_bit_3_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB58
int op_bit_3_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB59
int op_bit_3_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB5A
int op_bit_3_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB5B
int op_bit_3_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB5C
int op_bit_3_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB5D
int op_bit_3_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB5E
int op_bit_3_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB5F
int op_bit_4_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB60
int op_bit_4_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB61
int op_bit_4_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB62
int op_bit_4_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB63
int op_bit_4_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB64
int op_bit_4_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB65
int op_bit_4_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB66
int op_bit_4_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB67
int op_bit_5_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB68
int op_bit_5_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB69
int op_bit_5_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB6A
int op_bit_5_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB6B
int op_bit_5_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB6C
int op_bit_5_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB6D
int op_bit_5_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB6E
int op_bit_5_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB6F
int op_bit_6_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB70
int op_bit_6_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB71
int op_bit_6_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB72
int op_bit_6_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB73
int op_bit_6_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB74
int op_bit_6_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB75
int op_bit_6_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB76
int op_bit_6_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB77
int op_bit_7_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB78
int op_bit_7_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB79
int op_bit_7_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB7A
int op_bit_7_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB7B
int op_bit_7_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB7C
int op_bit_7_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB7D
int op_bit_7_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB7E
int op_bit_7_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB7F
int op_res_0_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB80
int op_res_0_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB81
int op_res_0_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB82
int op_res_0_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB83
int op_res_0_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB84
int op_res_0_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB85
int op_res_0_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB86
int op_res_0_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB87
int op_res_1_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB88
int op_res_1_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB89
int op_res_1_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB8A
int op_res_1_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB8B
int op_res_1_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB8C
int op_res_1_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB8D
int op_res_1_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB8E
int op_res_1_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB8F
int op_res_2_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB90
int op_res_2_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB91
int op_res_2_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB92
int op_res_2_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB93
int op_res_2_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB94
int op_res_2_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB95
int op_res_2_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB96
int op_res_2_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB97
int op_res_3_b(ProcessingUnit &cpu, MMU &mmu); // 0xCB98
int op_res_3_c(ProcessingUnit &cpu, MMU &mmu); // 0xCB99
int op_res_3_d(ProcessingUnit &cpu, MMU &mmu); // 0xCB9A
int op_res_3_e(ProcessingUnit &cpu, MMU &mmu); // 0xCB9B
int op_res_3_h(ProcessingUnit &cpu, MMU &mmu); // 0xCB9C
int op_res_3_l(ProcessingUnit &cpu, MMU &mmu); // 0xCB9D
int op_res_3_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCB9E
int op_res_3_a(ProcessingUnit &cpu, MMU &mmu); // 0xCB9F
int op_res_4_b(ProcessingUnit &cpu, MMU &mmu); // 0xCBA0
int op_res_4_c(ProcessingUnit &cpu, MMU &mmu); // 0xCBA1
int op_res_4_d(ProcessingUnit &cpu, MMU &mmu); // 0xCBA2
int op_res_4_e(ProcessingUnit &cpu, MMU &mmu); // 0xCBA3
int op_res_4_h(ProcessingUnit &cpu, MMU &mmu); // 0xCBA4
int op_res_4_l(ProcessingUnit &cpu, MMU &mmu); // 0xCBA5
int op_res_4_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCBA6
int op_res_4_a(ProcessingUnit &cpu, MMU &mmu); // 0xCBA7
int op_res_5_b(ProcessingUnit &cpu, MMU &mmu); // 0xCBA8
int op_res_5_c(ProcessingUnit &cpu, MMU &mmu); // 0xCBA9
int op_res_5_d(ProcessingUnit &cpu, MMU &mmu); // 0xCBAA
int op_res_5_e(ProcessingUnit &cpu, MMU &mmu); // 0xCBAB
int op_res_5_h(ProcessingUnit &cpu, MMU &mmu); // 0xCBAC
int op_res_5_l(ProcessingUnit &cpu, MMU &mmu); // 0xCBAD
int op_res_5_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCBAE
int op_res_5_a(ProcessingUnit &cpu, MMU &mmu); // 0xCBAF
int op_res_6_b(ProcessingUnit &cpu, MMU &mmu); // 0xCBB0
int op_res_6_c(ProcessingUnit &cpu, MMU &mmu); // 0xCBB1
int op_res_6_d(ProcessingUnit &cpu, MMU &mmu); // 0xCBB2
int op_res_6_e(ProcessingUnit &cpu, MMU &mmu); // 0xCBB3
int op_res_6_h(ProcessingUnit &cpu, MMU &mmu); // 0xCBB4
int op_res_6_l(ProcessingUnit &cpu, MMU &mmu); // 0xCBB5
int op_res_6_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCBB6
int op_res_6_a(ProcessingUnit &cpu, MMU &mmu); // 0xCBB7
int op_res_7_b(ProcessingUnit &cpu, MMU &mmu); // 0xCBB8
int op_res_7_c(ProcessingUnit &cpu, MMU &mmu); // 0xCBB9
int op_res_7_d(ProcessingUnit &cpu, MMU &mmu); // 0xCBBA
int op_res_7_e(ProcessingUnit &cpu, MMU &mmu); // 0xCBBB
int op_res_7_h(ProcessingUnit &cpu, MMU &mmu); // 0xCBBC
int op_res_7_l(ProcessingUnit &cpu, MMU &mmu); // 0xCBBD
int op_res_7_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCBBE
int op_res_7_a(ProcessingUnit &cpu, MMU &mmu); // 0xCBBF
int op_set_0_b(ProcessingUnit &cpu, MMU &mmu); // 0xCBC0
int op_set_0_c(ProcessingUnit &cpu, MMU &mmu); // 0xCBC1
int op_set_0_d(ProcessingUnit &cpu, MMU &mmu); // 0xCBC2
int op_set_0_e(ProcessingUnit &cpu, MMU &mmu); // 0xCBC3
int op_set_0_h(ProcessingUnit &cpu, MMU &mmu); // 0xCBC4
int op_set_0_l(ProcessingUnit &cpu, MMU &mmu); // 0xCBC5
int op_set_0_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCBC6
int op_set_0_a(ProcessingUnit &cpu, MMU &mmu); // 0xCBC7
int op_set_1_b(ProcessingUnit &cpu, MMU &mmu); // 0xCBC8
int op_set_1_c(ProcessingUnit &cpu, MMU &mmu); // 0xCBC9
int op_set_1_d(ProcessingUnit &cpu, MMU &mmu); // 0xCBCA
int op_set_1_e(ProcessingUnit &cpu, MMU &mmu); // 0xCBCB
int op_set_1_h(ProcessingUnit &cpu, MMU &mmu); // 0xCBCC
int op_set_1_l(ProcessingUnit &cpu, MMU &mmu); // 0xCBCD
int op_set_1_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCBCE
int op_set_1_a(ProcessingUnit &cpu, MMU &mmu); // 0xCBCF
int op_set_2_b(ProcessingUnit &cpu, MMU &mmu); // 0xCBD0
int op_set_2_c(ProcessingUnit &cpu, MMU &mmu); // 0xCBD1
int op_set_2_d(ProcessingUnit &cpu, MMU &mmu); // 0xCBD2
int op_set_2_e(ProcessingUnit &cpu, MMU &mmu); // 0xCBD3
int op_set_2_h(ProcessingUnit &cpu, MMU &mmu); // 0xCBD4
int op_set_2_l(ProcessingUnit &cpu, MMU &mmu); // 0xCBD5
int op_set_2_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCBD6
int op_set_2_a(ProcessingUnit &cpu, MMU &mmu); // 0xCBD7
int op_set_3_b(ProcessingUnit &cpu, MMU &mmu); // 0xCBD8
int op_set_3_c(ProcessingUnit &cpu, MMU &mmu); // 0xCBD9
int op_set_3_d(ProcessingUnit &cpu, MMU &mmu); // 0xCBDA
int op_set_3_e(ProcessingUnit &cpu, MMU &mmu); // 0xCBDB
int op_set_3_h(ProcessingUnit &cpu, MMU &mmu); // 0xCBDC
int op_set_3_l(ProcessingUnit &cpu, MMU &mmu); // 0xCBDD
int op_set_3_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCBDE
int op_set_3_a(ProcessingUnit &cpu, MMU &mmu); // 0xCBDF
int op_set_4_b(ProcessingUnit &cpu, MMU &mmu); // 0xCBE0
int op_set_4_c(ProcessingUnit &cpu, MMU &mmu); // 0xCBE1
int op_set_4_d(ProcessingUnit &cpu, MMU &mmu); // 0xCBE2
int op_set_4_e(ProcessingUnit &cpu, MMU &mmu); // 0xCBE3
int op_set_4_h(ProcessingUnit &cpu, MMU &mmu); // 0xCBE4
int op_set_4_l(ProcessingUnit &cpu, MMU &mmu); // 0xCBE5
int op_set_4_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCBE6
int op_set_4_a(ProcessingUnit &cpu, MMU &mmu); // 0xCBE7
int op_set_5_b(ProcessingUnit &cpu, MMU &mmu); // 0xCBE8
int op_set_5_c(ProcessingUnit &cpu, MMU &mmu); // 0xCBE9
int op_set_5_d(ProcessingUnit &cpu, MMU &mmu); // 0xCBEA
int op_set_5_e(ProcessingUnit &cpu, MMU &mmu); // 0xCBEB
int op_set_5_h(ProcessingUnit &cpu, MMU &mmu); // 0xCBEC
int op_set_5_l(ProcessingUnit &cpu, MMU &mmu); // 0xCBED
int op_set_5_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCBEE
int op_set_5_a(ProcessingUnit &cpu, MMU &mmu); // 0xCBEF
int op_set_6_b(ProcessingUnit &cpu, MMU &mmu); // 0xCBF0
int op_set_6_c(ProcessingUnit &cpu, MMU &mmu); // 0xCBF1
int op_set_6_d(ProcessingUnit &cpu, MMU &mmu); // 0xCBF2
int op_set_6_e(ProcessingUnit &cpu, MMU &mmu); // 0xCBF3
int op_set_6_h(ProcessingUnit &cpu, MMU &mmu); // 0xCBF4
int op_set_6_l(ProcessingUnit &cpu, MMU &mmu); // 0xCBF5
int op_set_6_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCBF6
int op_set_6_a(ProcessingUnit &cpu, MMU &mmu); // 0xCBF7
int op_set_7_b(ProcessingUnit &cpu, MMU &mmu); // 0xCBF8
int op_set_7_c(ProcessingUnit &cpu, MMU &mmu); // 0xCBF9
int op_set_7_d(ProcessingUnit &cpu, MMU &mmu); // 0xCBFA
int op_set_7_e(ProcessingUnit &cpu, MMU &mmu); // 0xCBFB
int op_set_7_h(ProcessingUnit &cpu, MMU &mmu); // 0xCBFC
int op_set_7_l(ProcessingUnit &cpu, MMU &mmu); // 0xCBFD
int op_set_7_hl(ProcessingUnit &cpu, MMU &mmu); // 0xCBFE
int op_set_7_a(ProcessingUnit &cpu, MMU &mmu); // 0xCBFF