#pragma once

#include "common.hpp"

class ProcessingUnit;
class MMU;

int op_nop(ProcessingUnit &cpu, MMU &mmu); // 0x00
int op_ld_bc_d16(ProcessingUnit &cpu, MMU &mmu); // 0x01
int op_ld_bc_a(ProcessingUnit &cpu, MMU &mmu); // 0x02
int op_inc_bc(ProcessingUnit &cpu, MMU &mmu); // 0x03
int op_inc_b(ProcessingUnit &cpu, MMU &mmu); // 0x04
int op_dec_b(ProcessingUnit &cpu, MMU &mmu); // 0x05
int op_ld_b_d8(ProcessingUnit &cpu, MMU &mmu); // 0x06
int op_rlca(ProcessingUnit &cpu, MMU &mmu); // 0x07
int op_ld_a16_sp(ProcessingUnit &cpu, MMU &mmu); // 0x08
int op_add_hl_bc(ProcessingUnit &cpu, MMU &mmu); // 0x09
int op_ld_a_bc(ProcessingUnit &cpu, MMU &mmu); // 0x0A
int op_dec_bc(ProcessingUnit &cpu, MMU &mmu); // 0x0B
int op_inc_c(ProcessingUnit &cpu, MMU &mmu); // 0x0C
int op_dec_c(ProcessingUnit &cpu, MMU &mmu); // 0x0D
int op_ld_c_d8(ProcessingUnit &cpu, MMU &mmu); // 0x0E
int op_rrca(ProcessingUnit &cpu, MMU &mmu); // 0x0F
int op_stop(ProcessingUnit &cpu, MMU &mmu); // 0x10
int op_ld_de_d16(ProcessingUnit &cpu, MMU &mmu); // 0x11
int op_ld_de_a(ProcessingUnit &cpu, MMU &mmu); // 0x12
int op_inc_de(ProcessingUnit &cpu, MMU &mmu); // 0x13
int op_inc_d(ProcessingUnit &cpu, MMU &mmu); // 0x14
int op_dec_d(ProcessingUnit &cpu, MMU &mmu); // 0x15
int op_ld_d_d8(ProcessingUnit &cpu, MMU &mmu); // 0x16
int op_rla(ProcessingUnit &cpu, MMU &mmu); // 0x17
int op_jr_r8(ProcessingUnit &cpu, MMU &mmu); // 0x18
int op_add_hl_de(ProcessingUnit &cpu, MMU &mmu); // 0x19
int op_ld_a_de(ProcessingUnit &cpu, MMU &mmu); // 0x1A
int op_dec_de(ProcessingUnit &cpu, MMU &mmu); // 0x1B
int op_inc_e(ProcessingUnit &cpu, MMU &mmu); // 0x1C
int op_dec_e(ProcessingUnit &cpu, MMU &mmu); // 0x1D
int op_ld_e_d8(ProcessingUnit &cpu, MMU &mmu); // 0x1E
int op_rra(ProcessingUnit &cpu, MMU &mmu); // 0x1F
int op_jr_nz(ProcessingUnit &cpu, MMU &mmu); // 0x20
int op_ld_hl_d16(ProcessingUnit &cpu, MMU &mmu); // 0x21
int op_ld_hli_a(ProcessingUnit &cpu, MMU &mmu); // 0x22
int op_inc_hl(ProcessingUnit &cpu, MMU &mmu); // 0x23
int op_inc_h(ProcessingUnit &cpu, MMU &mmu); // 0x24
int op_dec_h(ProcessingUnit &cpu, MMU &mmu); // 0x25
int op_ld_h_d8(ProcessingUnit &cpu, MMU &mmu); // 0x26
int op_daa(ProcessingUnit &cpu, MMU &mmu); // 0x27
int op_jr_z(ProcessingUnit &cpu, MMU &mmu); // 0x28
int op_add_hl_hl(ProcessingUnit &cpu, MMU &mmu); // 0x29
int op_ld_a_hli(ProcessingUnit &cpu, MMU &mmu); // 0x2A
int op_dec_hl(ProcessingUnit &cpu, MMU &mmu); // 0x2B
int op_inc_l(ProcessingUnit &cpu, MMU &mmu); // 0x2C
int op_dec_l(ProcessingUnit &cpu, MMU &mmu); // 0x2D
int op_ld_l_d8(ProcessingUnit &cpu, MMU &mmu); // 0x2E
int op_cpl(ProcessingUnit &cpu, MMU &mmu); // 0x2F
int op_jr_nc(ProcessingUnit &cpu, MMU &mmu); // 0x30
int op_ld_sp_d16(ProcessingUnit &cpu, MMU &mmu); // 0x31
int op_ld_hld_a(ProcessingUnit &cpu, MMU &mmu); // 0x32
int op_inc_sp(ProcessingUnit &cpu, MMU &mmu); // 0x33
int op_inc_hl_ptr(ProcessingUnit &cpu, MMU &mmu); // 0x34
int op_dec_hl_ptr(ProcessingUnit &cpu, MMU &mmu); // 0x35
int op_ld_hl_d8(ProcessingUnit &cpu, MMU &mmu); // 0x36
int op_scf(ProcessingUnit &cpu, MMU &mmu); // 0x37
int op_jr_c(ProcessingUnit &cpu, MMU &mmu); // 0x38
int op_add_hl_sp(ProcessingUnit &cpu, MMU &mmu); // 0x39
int op_ld_a_hld(ProcessingUnit &cpu, MMU &mmu); // 0x3A
int op_dec_sp(ProcessingUnit &cpu, MMU &mmu); // 0x3B
int op_inc_a(ProcessingUnit &cpu, MMU &mmu); // 0x3C
int op_dec_a(ProcessingUnit &cpu, MMU &mmu); // 0x3D
int op_ld_a_d8(ProcessingUnit &cpu, MMU &mmu); // 0x3E
int op_ccf(ProcessingUnit &cpu, MMU &mmu); // 0x3F
int op_ld_b_b(ProcessingUnit &cpu, MMU &mmu); // 0x40
int op_ld_b_c(ProcessingUnit &cpu, MMU &mmu); // 0x41
int op_ld_b_d(ProcessingUnit &cpu, MMU &mmu); // 0x42
int op_ld_b_e(ProcessingUnit &cpu, MMU &mmu); // 0x43
int op_ld_b_h(ProcessingUnit &cpu, MMU &mmu); // 0x44
int op_ld_b_l(ProcessingUnit &cpu, MMU &mmu); // 0x45
int op_ld_b_hl(ProcessingUnit &cpu, MMU &mmu); // 0x46
int op_ld_b_a(ProcessingUnit &cpu, MMU &mmu); // 0x47
int op_ld_c_b(ProcessingUnit &cpu, MMU &mmu); // 0x48
int op_ld_c_c(ProcessingUnit &cpu, MMU &mmu); // 0x49
int op_ld_c_d(ProcessingUnit &cpu, MMU &mmu); // 0x4A
int op_ld_c_e(ProcessingUnit &cpu, MMU &mmu); // 0x4B
int op_ld_c_h(ProcessingUnit &cpu, MMU &mmu); // 0x4C
int op_ld_c_l(ProcessingUnit &cpu, MMU &mmu); // 0x4D
int op_ld_c_hl(ProcessingUnit &cpu, MMU &mmu); // 0x4E
int op_ld_c_a(ProcessingUnit &cpu, MMU &mmu); // 0x4F
int op_ld_d_b(ProcessingUnit &cpu, MMU &mmu); // 0x50
int op_ld_d_c(ProcessingUnit &cpu, MMU &mmu); // 0x51
int op_ld_d_d(ProcessingUnit &cpu, MMU &mmu); // 0x52
int op_ld_d_e(ProcessingUnit &cpu, MMU &mmu); // 0x53
int op_ld_d_h(ProcessingUnit &cpu, MMU &mmu); // 0x54
int op_ld_d_l(ProcessingUnit &cpu, MMU &mmu); // 0x55
int op_ld_d_hl(ProcessingUnit &cpu, MMU &mmu); // 0x56
int op_ld_d_a(ProcessingUnit &cpu, MMU &mmu); // 0x57
int op_ld_e_b(ProcessingUnit &cpu, MMU &mmu); // 0x58
int op_ld_e_c(ProcessingUnit &cpu, MMU &mmu); // 0x59
int op_ld_e_d(ProcessingUnit &cpu, MMU &mmu); // 0x5A
int op_ld_e_e(ProcessingUnit &cpu, MMU &mmu); // 0x5B
int op_ld_e_h(ProcessingUnit &cpu, MMU &mmu); // 0x5C
int op_ld_e_l(ProcessingUnit &cpu, MMU &mmu); // 0x5D
int op_ld_e_hl(ProcessingUnit &cpu, MMU &mmu); // 0x5E
int op_ld_e_a(ProcessingUnit &cpu, MMU &mmu); // 0x5F
int op_ld_h_b(ProcessingUnit &cpu, MMU &mmu); // 0x60
int op_ld_h_c(ProcessingUnit &cpu, MMU &mmu); // 0x61
int op_ld_h_d(ProcessingUnit &cpu, MMU &mmu); // 0x62
int op_ld_h_e(ProcessingUnit &cpu, MMU &mmu); // 0x63
int op_ld_h_h(ProcessingUnit &cpu, MMU &mmu); // 0x64
int op_ld_h_l(ProcessingUnit &cpu, MMU &mmu); // 0x65
int op_ld_h_hl(ProcessingUnit &cpu, MMU &mmu); // 0x66
int op_ld_h_a(ProcessingUnit &cpu, MMU &mmu); // 0x67
int op_ld_l_b(ProcessingUnit &cpu, MMU &mmu); // 0x68
int op_ld_l_c(ProcessingUnit &cpu, MMU &mmu); // 0x69
int op_ld_l_d(ProcessingUnit &cpu, MMU &mmu); // 0x6A
int op_ld_l_e(ProcessingUnit &cpu, MMU &mmu); // 0x6B
int op_ld_l_h(ProcessingUnit &cpu, MMU &mmu); // 0x6C
int op_ld_l_l(ProcessingUnit &cpu, MMU &mmu); // 0x6D
int op_ld_l_hl(ProcessingUnit &cpu, MMU &mmu); // 0x6E
int op_ld_l_a(ProcessingUnit &cpu, MMU &mmu); // 0x6F
int op_ld_hl_b(ProcessingUnit &cpu, MMU &mmu); // 0x70
int op_ld_hl_c(ProcessingUnit &cpu, MMU &mmu); // 0x71
int op_ld_hl_d(ProcessingUnit &cpu, MMU &mmu); // 0x72
int op_ld_hl_e(ProcessingUnit &cpu, MMU &mmu); // 0x73
int op_ld_hl_h(ProcessingUnit &cpu, MMU &mmu); // 0x74
int op_ld_hl_l(ProcessingUnit &cpu, MMU &mmu); // 0x75
int op_halt(ProcessingUnit &cpu, MMU &mmu); // 0x76
int op_ld_hl_a(ProcessingUnit &cpu, MMU &mmu); // 0x77
int op_ld_a_b(ProcessingUnit &cpu, MMU &mmu); // 0x78
int op_ld_a_c_79(ProcessingUnit &cpu, MMU &mmu); // 0x79
int op_ld_a_d(ProcessingUnit &cpu, MMU &mmu); // 0x7A
int op_ld_a_e(ProcessingUnit &cpu, MMU &mmu); // 0x7B
int op_ld_a_h(ProcessingUnit &cpu, MMU &mmu); // 0x7C
int op_ld_a_l(ProcessingUnit &cpu, MMU &mmu); // 0x7D
int op_ld_a_hl(ProcessingUnit &cpu, MMU &mmu); // 0x7E
int op_ld_a_a(ProcessingUnit &cpu, MMU &mmu); // 0x7F
int op_add_a_b(ProcessingUnit &cpu, MMU &mmu); // 0x80
int op_add_a_c(ProcessingUnit &cpu, MMU &mmu); // 0x81
int op_add_a_d(ProcessingUnit &cpu, MMU &mmu); // 0x82
int op_add_a_e(ProcessingUnit &cpu, MMU &mmu); // 0x83
int op_add_a_h(ProcessingUnit &cpu, MMU &mmu); // 0x84
int op_add_a_l(ProcessingUnit &cpu, MMU &mmu); // 0x85
int op_add_a_hl(ProcessingUnit &cpu, MMU &mmu); // 0x86
int op_add_a_a(ProcessingUnit &cpu, MMU &mmu); // 0x87
int op_adc_a_b(ProcessingUnit &cpu, MMU &mmu); // 0x88
int op_adc_a_c(ProcessingUnit &cpu, MMU &mmu); // 0x89
int op_adc_a_d(ProcessingUnit &cpu, MMU &mmu); // 0x8A
int op_adc_a_e(ProcessingUnit &cpu, MMU &mmu); // 0x8B
int op_adc_a_h(ProcessingUnit &cpu, MMU &mmu); // 0x8C
int op_adc_a_l(ProcessingUnit &cpu, MMU &mmu); // 0x8D
int op_adc_a_hl(ProcessingUnit &cpu, MMU &mmu); // 0x8E
int op_adc_a_a(ProcessingUnit &cpu, MMU &mmu); // 0x8F
int op_sub_b(ProcessingUnit &cpu, MMU &mmu); // 0x90
int op_sub_c(ProcessingUnit &cpu, MMU &mmu); // 0x91
int op_sub_d(ProcessingUnit &cpu, MMU &mmu); // 0x92
int op_sub_e(ProcessingUnit &cpu, MMU &mmu); // 0x93
int op_sub_h(ProcessingUnit &cpu, MMU &mmu); // 0x94
int op_sub_l(ProcessingUnit &cpu, MMU &mmu); // 0x95
int op_sub_hl(ProcessingUnit &cpu, MMU &mmu); // 0x96
int op_sub_a(ProcessingUnit &cpu, MMU &mmu); // 0x97
int op_sbc_a_b(ProcessingUnit &cpu, MMU &mmu); // 0x98
int op_sbc_a_c(ProcessingUnit &cpu, MMU &mmu); // 0x99
int op_sbc_a_d(ProcessingUnit &cpu, MMU &mmu); // 0x9A
int op_sbc_a_e(ProcessingUnit &cpu, MMU &mmu); // 0x9B
int op_sbc_a_h(ProcessingUnit &cpu, MMU &mmu); // 0x9C
int op_sbc_a_l(ProcessingUnit &cpu, MMU &mmu); // 0x9D
int op_sbc_a_hl(ProcessingUnit &cpu, MMU &mmu); // 0x9E
int op_sbc_a_a(ProcessingUnit &cpu, MMU &mmu); // 0x9F
int op_and_b(ProcessingUnit &cpu, MMU &mmu); // 0xA0
int op_and_c(ProcessingUnit &cpu, MMU &mmu); // 0xA1
int op_and_d(ProcessingUnit &cpu, MMU &mmu); // 0xA2
int op_and_e(ProcessingUnit &cpu, MMU &mmu); // 0xA3
int op_and_h(ProcessingUnit &cpu, MMU &mmu); // 0xA4
int op_and_l(ProcessingUnit &cpu, MMU &mmu); // 0xA5
int op_and_hl(ProcessingUnit &cpu, MMU &mmu); // 0xA6
int op_and_a(ProcessingUnit &cpu, MMU &mmu); // 0xA7
int op_xor_b(ProcessingUnit &cpu, MMU &mmu); // 0xA8
int op_xor_c(ProcessingUnit &cpu, MMU &mmu); // 0xA9
int op_xor_d(ProcessingUnit &cpu, MMU &mmu); // 0xAA
int op_xor_e(ProcessingUnit &cpu, MMU &mmu); // 0xAB
int op_xor_h(ProcessingUnit &cpu, MMU &mmu); // 0xAC
int op_xor_l(ProcessingUnit &cpu, MMU &mmu); // 0xAD
int op_xor_hl(ProcessingUnit &cpu, MMU &mmu); // 0xAE
int op_xor_a(ProcessingUnit &cpu, MMU &mmu); // 0xAF
int op_or_b(ProcessingUnit &cpu, MMU &mmu); // 0xB0
int op_or_c(ProcessingUnit &cpu, MMU &mmu); // 0xB1
int op_or_d(ProcessingUnit &cpu, MMU &mmu); // 0xB2
int op_or_e(ProcessingUnit &cpu, MMU &mmu); // 0xB3
int op_or_h(ProcessingUnit &cpu, MMU &mmu); // 0xB4
int op_or_l(ProcessingUnit &cpu, MMU &mmu); // 0xB5
int op_or_hl(ProcessingUnit &cpu, MMU &mmu); // 0xB6
int op_or_a(ProcessingUnit &cpu, MMU &mmu); // 0xB7
int op_cp_b(ProcessingUnit &cpu, MMU &mmu); // 0xB8
int op_cp_c(ProcessingUnit &cpu, MMU &mmu); // 0xB9
int op_cp_d(ProcessingUnit &cpu, MMU &mmu); // 0xBA
int op_cp_e(ProcessingUnit &cpu, MMU &mmu); // 0xBB
int op_cp_h(ProcessingUnit &cpu, MMU &mmu); // 0xBC
int op_cp_l(ProcessingUnit &cpu, MMU &mmu); // 0xBD
int op_cp_hl(ProcessingUnit &cpu, MMU &mmu); // 0xBE
int op_cp_a(ProcessingUnit &cpu, MMU &mmu); // 0xBF
int op_ret_nz(ProcessingUnit &cpu, MMU &mmu); // 0xC0
int op_pop_bc(ProcessingUnit &cpu, MMU &mmu); // 0xC1
int op_jp_nz(ProcessingUnit &cpu, MMU &mmu); // 0xC2
int op_jp(ProcessingUnit &cpu, MMU &mmu); // 0xC3
int op_call_nz(ProcessingUnit &cpu, MMU &mmu); // 0xC4
int op_push_bc(ProcessingUnit &cpu, MMU &mmu); // 0xC5
int op_add_a_d8(ProcessingUnit &cpu, MMU &mmu); // 0xC6
int op_rst_00(ProcessingUnit &cpu, MMU &mmu); // 0xC7
int op_ret_z(ProcessingUnit &cpu, MMU &mmu); // 0xC8
int op_ret(ProcessingUnit &cpu, MMU &mmu); // 0xC9
int op_jp_z(ProcessingUnit &cpu, MMU &mmu); // 0xCA
int op_cb_prefix(ProcessingUnit &cpu, MMU &mmu); // 0xCB
int op_call_z(ProcessingUnit &cpu, MMU &mmu); // 0xCC
int op_call(ProcessingUnit &cpu, MMU &mmu); // 0xCD
int op_adc_a_d8(ProcessingUnit &cpu, MMU &mmu); // 0xCE
int op_rst_08(ProcessingUnit &cpu, MMU &mmu); // 0xCF
int op_ret_nc(ProcessingUnit &cpu, MMU &mmu); // 0xD0
int op_pop_de(ProcessingUnit &cpu, MMU &mmu); // 0xD1
int op_jp_nc(ProcessingUnit &cpu, MMU &mmu); // 0xD2
int op_illegal_d3(ProcessingUnit &cpu, MMU &mmu); // 0xD3
int op_call_nc(ProcessingUnit &cpu, MMU &mmu); // 0xD4
int op_push_de(ProcessingUnit &cpu, MMU &mmu); // 0xD5
int op_sub_d8(ProcessingUnit &cpu, MMU &mmu); // 0xD6
int op_rst_10(ProcessingUnit &cpu, MMU &mmu); // 0xD7
int op_ret_c(ProcessingUnit &cpu, MMU &mmu); // 0xD8
int op_reti(ProcessingUnit &cpu, MMU &mmu); // 0xD9
int op_jp_c(ProcessingUnit &cpu, MMU &mmu); // 0xDA
int op_illegal_db(ProcessingUnit &cpu, MMU &mmu); // 0xDB
int op_call_c(ProcessingUnit &cpu, MMU &mmu); // 0xDC
int op_illegal_dd(ProcessingUnit &cpu, MMU &mmu); // 0xDD
int op_sbc_a_d8(ProcessingUnit &cpu, MMU &mmu); // 0xDE
int op_rst_18(ProcessingUnit &cpu, MMU &mmu); // 0xDF
int op_ldh_a8_a(ProcessingUnit &cpu, MMU &mmu); // 0xE0
int op_pop_hl(ProcessingUnit &cpu, MMU &mmu); // 0xE1
int op_ld_c_a(ProcessingUnit &cpu, MMU &mmu); // 0xE2
int op_illegal_e3(ProcessingUnit &cpu, MMU &mmu); // 0xE3
int op_illegal_e4(ProcessingUnit &cpu, MMU &mmu); // 0xE4
int op_push_hl(ProcessingUnit &cpu, MMU &mmu); // 0xE5
int op_and_d8(ProcessingUnit &cpu, MMU &mmu); // 0xE6
int op_rst_20(ProcessingUnit &cpu, MMU &mmu); // 0xE7
int op_add_sp_e8(ProcessingUnit &cpu, MMU &mmu); // 0xE8
int op_jp_hl(ProcessingUnit &cpu, MMU &mmu); // 0xE9
int op_ld_a16_a(ProcessingUnit &cpu, MMU &mmu); // 0xEA
int op_illegal_eb(ProcessingUnit &cpu, MMU &mmu); // 0xEB
int op_illegal_ec(ProcessingUnit &cpu, MMU &mmu); // 0xEC
int op_illegal_ed(ProcessingUnit &cpu, MMU &mmu); // 0xED
int op_xor_d8(ProcessingUnit &cpu, MMU &mmu); // 0xEE
int op_rst_28(ProcessingUnit &cpu, MMU &mmu); // 0xEF
int op_ldh_a_a8(ProcessingUnit &cpu, MMU &mmu); // 0xF0
int op_pop_af(ProcessingUnit &cpu, MMU &mmu); // 0xF1
int op_ld_a_c_f2(ProcessingUnit &cpu, MMU &mmu); // 0xF2
int op_di(ProcessingUnit &cpu, MMU &mmu); // 0xF3
int op_illegal_f4(ProcessingUnit &cpu, MMU &mmu); // 0xF4
int op_push_af(ProcessingUnit &cpu, MMU &mmu); // 0xF5
int op_or_d8(ProcessingUnit &cpu, MMU &mmu); // 0xF6
int op_rst_30(ProcessingUnit &cpu, MMU &mmu); // 0xF7
int op_ld_hl_sp_e8(ProcessingUnit &cpu, MMU &mmu); // 0xF8
int op_ld_sp_hl(ProcessingUnit &cpu, MMU &mmu); // 0xF9
int op_ld_a_a16(ProcessingUnit &cpu, MMU &mmu); // 0xFA
int op_ei(ProcessingUnit &cpu, MMU &mmu); // 0xFB
int op_illegal_fc(ProcessingUnit &cpu, MMU &mmu); // 0xFC
int op_illegal_fd(ProcessingUnit &cpu, MMU &mmu); // 0xFD
int op_cp_d8(ProcessingUnit &cpu, MMU &mmu); // 0xFE
int op_rst_38(ProcessingUnit &cpu, MMU &mmu); // 0xFF